# Generated by Django 4.2.6 on 2024-01-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
